MODEL:
  META_ARCHITECTURE: Yolo
  YAML: yolov5m.yaml
  BACKBONE:
    NAME: build_darknet_backbone
  YOLO:
    FOCAL_LOSS_GAMMA: 0.0
    BOX_LOSS_GAIN: 0.05
    CLS_LOSS_GAIN: 0.3
    CLS_POSITIVE_WEIGHT: 1.0
    OBJ_LOSS_GAIN: 0.7
    OBJ_POSITIVE_WEIGHT: 1.0
    LABEL_SMOOTHING: 0.0
    ANCHOR_T: 4.0
    CONF_THRESH: 0.001
    IOU_THRES: 0.65
  PIXEL_MEAN: [0.0, 0.0, 0.0]
  PIXEL_STD: [255.0, 255.0, 255.0]
SOLVER:
  BASE_LR: 0.01
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_NORM: 0.0
  WEIGHT_DECAY_BIAS: 0.0001
  LR_SCHEDULER_NAME: WarmupCosineLR
  WARMUP_ITERS: 10000
  MAX_ITER: 200000
  IMS_PER_BATCH: 16
INPUT:  # Uses Yolo's own transforms
  SIZE: 416
  HSV_H: 0.015
  HSV_S: 0.7
  HSV_V: 0.4
  DEGREES: 0.0
  TRANSLATE: 0.1
  SCALE: 0.5
  SHEAR: 0.0
  PERSPECTIVE: 0.0
  FLIPUD: 0.0
  FLIPLR: 0.5
  MOSAIC: 1.0   # IGNORED
  MIXUP: 0.0
  FORMAT: BGR
OUTPUT_DIR: ./outputs/exp
TEST:
  AUG:
    SIZE: 416
    FLIP: False
  EVAL_PERIOD: 4000
