_BASE_: "Base-Yolo.yaml"
MODEL:
  YAML: configs/yolov4-tiny.yaml
SOLVER:
  IMS_PER_BATCH: 32
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
OUTPUT_DIR: ./outputs/v4-tiny
VERSION: 2