_BASE_: "Base-YoloV5.yaml"
MODEL:
  WEIGHTS: weights/yolov5mD2-Full.pth
  YAML: configs/yolov5m.yaml
  QUANTIZATION:
    scope: [
            # backbone
            'backbone',
            # Head
            'head',
           ]
    keyword: ["debug", "dorefa", "lsq"]
    stable: 10000
    fm_enable: True 
    wt_enable: True 
    padding_after_quant: True
    fm_bit: 4.0
    wt_bit: 4.0
    fm_boundary: 1.0
    wt_boundary: 1.0
    fm_half_range: False
    wt_quant_group: 1
    wt_adaptive: "var-mean"
    policy: 'configs/policy_yolov5m-fixpoint.txt'
SOLVER:
  BASE_LR: 0.01
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_NORM: 0.0
  WEIGHT_DECAY_BIAS: 0.0001
  LR_SCHEDULER_NAME: WarmupCosineLR
  WARMUP_ITERS: 5000
  MAX_ITER: 90000
  IMS_PER_BATCH: 16
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
OUTPUT_DIR: './outputs/QAT-4bit-stable'
VERSION: 2